export const SET_LOGIN_ACCOUNT = 'SET_LOGIN_ACCOUNT';
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_SIGNUP_ACCOUNT = 'SET_SIGNUP_ACCOUNT';
export const SET_SIGNUP_USERNAME = 'SET_SIGNUP_USERNAME';
export const SET_SIGNUP_PASSWORD = 'SET_SIGNUP_PASSWORD';
export const SET_SIGNUP_CONFIRM_PASSWORD = 'SET_SIGNUP_CONFIRM_PASSWORD';
export const SET_SIGNUP_MESSAGE = 'SET_SIGNUP_MESSAGE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGOUT = 'LOGOUT';


export const CONNECT_WEB_SOCKET = 'CONNECT_WEB_SOCKET';
export const CONNECT_WEB_SOCKET_SUCCESS = 'CONNECT_WEB_SOCKET_SUCCESS';
export const CONNECT_WEB_SOCKET_FAIL = 'CONNECT_WEB_SOCKET_FAIL';
export const DISCONNECT_WEB_SOCKET = 'DISCONNECT_WEB_SOCKET';
export const SET_MESSAGE_BOX = 'SET_MESSAGE_BOX';
export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_MESSAGE_BOX_STYLE = 'SET_MESSAGE_BOX_STYLE';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_DRAWER_OPEN = 'SET_DRAWER_OPEN';
export const SET_CHAT_PEOPLE = 'SET_CHAT_PEOPLE';
export const SET_NEW_MESSAGE_ALARM = 'SET_NEW_MESSAGE_ALARM';
export const SET_IMAGE_MODAL = 'SET_IMAGE_MODAL'




