/* Login related */
export const SET_LOGIN_ACCOUNT = 'SET_LOGIN_ACCOUNT';
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

/* Signup related */
export const SET_SIGNUP_ACCOUNT = 'SET_SIGNUP_ACCOUNT';
export const SET_SIGNUP_USERNAME = 'SET_SIGNUP_USERNAME';
export const SET_SIGNUP_PASSWORD = 'SET_SIGNUP_PASSWORD';
export const SET_SIGNUP_CONFIRM_PASSWORD = 'SET_SIGNUP_CONFIRM_PASSWORD';
export const SET_SIGNUP_MESSAGE = 'SET_SIGNUP_MESSAGE';
export const SET_SIGNUP_UPLOAD_FILE_NAME = 'SET_SIGNUP_UPLOAD_FILE_NAME';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SET_SUCCESS_DIALOG = 'SET_SUCCESS_DIALOG';

/* Edit user information related */
export const GET_USER_ACCOUNT_REQUEST = 'GET_USER_ACCOUNT_REQUEST';
export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS';
export const GET_USER_ACCOUNT_FAIL = 'GET_USER_ACCOUNT_FAIL';
export const SET_EDIT_USER_NAME = 'SET_EDIT_USER_NAME';
export const SET_EDIT_FILE_NAME = 'SET_EDIT_FILE_NAME';
export const SET_EDIT_MESSAGE = 'SET_EDIT_MESSAGE';
export const EDIT_USER_INFO_REQUEST = 'EDIT_USER_INFO_REQUEST';
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const EDIT_USER_INFO_FAIL = 'EDIT_USER_INFO_FAIL';
export const SET_EDIT_SUCCESS_DIALOG = 'SET_EDIT_SUCCESS_DIALOG';


/* Chat room related */
export const CONNECT_WEB_SOCKET = 'CONNECT_WEB_SOCKET';
export const CONNECT_WEB_SOCKET_SUCCESS = 'CONNECT_WEB_SOCKET_SUCCESS';
export const CONNECT_WEB_SOCKET_FAIL = 'CONNECT_WEB_SOCKET_FAIL';
export const SET_WEB_SOCKET_IS_LISTENING = 'SET_WEB_SOCKET_IS_LISTENING';
export const DISCONNECT_WEB_SOCKET = 'DISCONNECT_WEB_SOCKET';
export const SET_MESSAGE_BOX = 'SET_MESSAGE_BOX';
export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_MESSAGE_BOX_STYLE = 'SET_MESSAGE_BOX_STYLE';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_DRAWER_OPEN = 'SET_DRAWER_OPEN';
export const SET_CHAT_PEOPLE = 'SET_CHAT_PEOPLE';
export const SET_NEW_MESSAGE_ALARM = 'SET_NEW_MESSAGE_ALARM';
export const SET_IMAGE_MODAL = 'SET_IMAGE_MODAL'




