export const SET_USER_ACCOUNT = 'SET_USER_ACCOUNT';
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const CONNECT_WEB_SOCKET = 'CONNECT_WEB_SOCKET';
export const CONNECT_WEB_SOCKET_SUCCESS = 'CONNECT_WEB_SOCKET_SUCCESS';
export const CONNECT_WEB_SOCKET_FAIL = 'CONNECT_WEB_SOCKET_FAIL';
export const SET_MESSAGE_BOX = 'SET_MESSAGE_BOX';
export const SET_ONLINE_COUNT = 'SET_ONLINE_COUNT';
